"""initial schema

Revision ID: 1b66b182c6f8
Revises: 
Create Date: 2026-03-23 21:42:40.352538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b66b182c6f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_hash', sa.String(length=128), nullable=False),
    sa.Column('output_hash', sa.String(length=128), nullable=False),
    sa.Column('state_from', sa.String(length=32), nullable=False),
    sa.Column('state_to', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('confidence_scores', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_agent', 'audit_log', ['agent'], unique=False)
    op.create_index('ix_audit_log_timestamp', 'audit_log', ['timestamp'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('transaction_id', sa.String(length=64), nullable=False),
    sa.Column('account_name', sa.String(length=256), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=False),
    sa.Column('reference_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index('ix_bank_transactions_reference_id', 'bank_transactions', ['reference_id'], unique=False)
    op.create_table('documents',
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('source_email', sa.String(length=256), nullable=False),
    sa.Column('account_name', sa.String(length=256), nullable=True),
    sa.Column('amount', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('bank_reference_id', sa.String(length=128), nullable=True),
    sa.Column('payment_date', sa.String(length=32), nullable=True),
    sa.Column('attachment_mime_type', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index('ix_documents_state', 'documents', ['state'], unique=False)
    op.create_table('match_results',
    sa.Column('match_id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('bank_transaction_id', sa.String(length=64), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('amount_delta', sa.Float(), nullable=False),
    sa.Column('name_similarity', sa.Float(), nullable=True),
    sa.Column('bank_reference_id_match', sa.Boolean(), nullable=False),
    sa.Column('temporal_delta_days', sa.Integer(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index('ix_match_results_document_id', 'match_results', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_match_results_document_id', table_name='match_results')
    op.drop_table('match_results')
    op.drop_index('ix_documents_state', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_bank_transactions_reference_id', table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index('ix_audit_log_timestamp', table_name='audit_log')
    op.drop_index('ix_audit_log_agent', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
